services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-C.nemesis123}
    volumes:
      - mongodb_data:/data/db
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=5000
      - FRONTEND_URL=http://frontend:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://145.223.81.130:5000/api
    ports:
      - "3000:3000"   # hostPort:containerPort — hostta 3000 meşgulse "3001:3000" kullan
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://145.223.81.130:5000/api
      - NODE_ENV=production
    networks:
      - appnet
    restart: unless-stopped

volumes:
  mongodb_data:

networks:
  appnet:
    driver: bridge